include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # === Boas práticas ===
    prefer_const_constructors: true      # Use const sempre que possível
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    avoid_print: true                    # Não use print em produção, prefira logger
    avoid_unnecessary_containers: true
    prefer_final_fields: true            # Torna campos imutáveis quando possível
    prefer_single_quotes: true           # Usa aspas simples por padrão

    # === Null safety e legibilidade ===
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    always_use_package_imports: true     # Evita imports relativos confusos
    avoid_relative_lib_imports: true

    # === Estilo e organização ===
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    constant_identifier_names: false     # Permite constantes em maiúsculo (ex: API_URL)
    non_constant_identifier_names: false # Permite variáveis com camelCase

    # === Performance ===
    avoid_redundant_argument_values: true
    unnecessary_await_in_return: true

analyzer:
  exclude:
    - "**/*.g.dart"      # Arquivos gerados (json_serializable, etc)
    - "**/*.freezed.dart"
